import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.awt.*;
import javax.swing.JComboBox;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class Member extends javax.swing.JFrame {

    /**
     * Creates new form Member
     */
    public Member() {
        initComponents();
    }
    
    public void combo_box(){
        JComboBox combostatus = new JComboBox();
        combostatus.removeAllItems();
        combostatus.addItem("09:00-12:00");
        combostatus.addItem("12:00-15:00");
        combostatus.addItem("15:00-18:00");
        combostatus.addItem("18:00-21:00");
        
        for (int i = 1; i <=4; i++) {
            combostatus.addItem(i);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tAge = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        tTime = new javax.swing.JComboBox<>();
        tPayment = new javax.swing.JTextField();
        tEmail = new javax.swing.JTextField();
        tPhone = new javax.swing.JTextField();
        tName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 160, 80));

        tAge.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAgeActionPerformed(evt);
            }
        });
        jPanel1.add(tAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 340, 310, 40));

        jButton3.setText("reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(913, 590, 160, 50));

        jButton2.setText("save");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 590, 160, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close-button-png-30241_adobespark.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 60, 40, 40));

        tTime.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        tTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTimeActionPerformed(evt);
            }
        });
        jPanel1.add(tTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 310, 40));

        tPayment.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(tPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 450, 310, 40));

        tEmail.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEmailActionPerformed(evt);
            }
        });
        jPanel1.add(tEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 310, 40));

        tPhone.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPhoneActionPerformed(evt);
            }
        });
        jPanel1.add(tPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 310, 40));

        tName.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel1.add(tName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 310, 40));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/new member.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1160, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPhoneActionPerformed

    private void tEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tEmailActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost/db_gym","root","");
            con.createStatement().executeUpdate("INSERT INTO member VALUES"+"(null,'"+tName.getText()+"','"+tPhone.getText()+"','"+tEmail.getText()+
                    "','"+tTime.getSelectedItem()+"','"+tAge.getText()+"', '"+tPayment.getText()+"')");
            
            refresh();
            JOptionPane.showMessageDialog(null, "Daftar Berhasil");
            new HOME().setVisible(true);
        } catch (SQLException ex) {
            Logger.getLogger(Member.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tAgeActionPerformed

    private void tTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField tAge;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tName;
    private javax.swing.JTextField tPayment;
    private javax.swing.JTextField tPhone;
    private javax.swing.JComboBox<String> tTime;
    // End of variables declaration//GEN-END:variables
    private void refresh() {
        tName.setText("");
        tPhone.setText("");
        tEmail.setText("");
        tTime.setSelectedItem("");
        tAge.setText("");
        tPayment.setText("");
    }
}
