
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author asus
 */
public class updateMember extends javax.swing.JFrame {

    /**
     * Creates new form updateMember
     */
    public updateMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnRefresh = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        tSearch = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tTime = new javax.swing.JComboBox<>();
        tPayment = new javax.swing.JTextField();
        tAge = new javax.swing.JTextField();
        tEmail = new javax.swing.JTextField();
        tPhone = new javax.swing.JTextField();
        tName = new javax.swing.JTextField();
        tId = new javax.swing.JTextField();
        asdasdasdsda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRefresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRefreshMouseClicked(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, 160, 50));

        btnSearch.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSearch.setText("S E A R C H");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 90, 160, 50));

        tSearch.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        tSearch.setToolTipText("");
        tSearch.setName(""); // NOI18N
        tSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tSearchMouseClicked(evt);
            }
        });
        tSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tSearchActionPerformed(evt);
            }
        });
        jPanel1.add(tSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 470, 60));
        tSearch.getAccessibleContext().setAccessibleName("");

        btnUpdate.setText("    ");
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 580, 160, 50));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/close-button-png-30241_adobespark.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 10, 40, 40));

        tTime.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5" }));
        tTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTimeActionPerformed(evt);
            }
        });
        jPanel1.add(tTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 250, 260, 40));
        jPanel1.add(tPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 450, 260, 40));
        jPanel1.add(tAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 340, 260, 40));
        jPanel1.add(tEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 260, 40));
        jPanel1.add(tPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 260, 40));
        jPanel1.add(tName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 260, 40));
        jPanel1.add(tId, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 260, 40));

        asdasdasdsda.setIcon(new javax.swing.ImageIcon("C:\\Users\\asus\\OneDrive\\Documents\\0. SIMBOL\\update.png")); // NOI18N
        asdasdasdsda.setText("jLabel1");
        asdasdasdsda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asdasdasdsdaMouseClicked(evt);
            }
        });
        jPanel1.add(asdasdasdsda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1158, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTimeActionPerformed

    private void asdasdasdsdaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asdasdasdsdaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_asdasdasdsdaMouseClicked

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            java.sql.Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_gym","root","");
            koneksi.createStatement().executeUpdate("UPDATE member SET name='"+tName.getText()+"', phone_number='"+tPhone.getText()+"', "
                    + "email='"+tEmail.getText()+"', gym_time='"+tTime.getSelectedItem()+"', age='"+tAge.getText()+"', "
                    + "payment='"+tPayment.getText()+"' WHERE id_member='"+tId.getText()+"'");
            
            refresh();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diganti");
            setVisible(false);
        } 
        catch (SQLException ex) {
            Logger.getLogger(updateMember.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateMouseClicked

    private void tSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tSearchActionPerformed

    private void tSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tSearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tSearchMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try{
            java.sql.Connection koneksi = DriverManager.getConnection("jdbc:mysql://localhost/db_gym","root","");
            ResultSet rs = koneksi.createStatement().executeQuery("SELECT * FROM member WHERE id_member='"+tSearch.getText()+"'");
            
            while(rs.next()){
                tId.setText(rs.getString("id_member"));
                tName.setText(rs.getString("name"));
                tPhone.setText(rs.getString("phone_number"));
                tEmail.setText(rs.getString("email"));
                tTime.setSelectedItem(rs.getString("gym_time"));
                tAge.setText(rs.getString("age"));
                tPayment.setText(rs.getString("payment"));
            }
        }catch(SQLException ex){
            Logger.getLogger(updateMember.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnRefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRefreshMouseClicked
        // TODO add your handling code here:
        refresh();
    }//GEN-LAST:event_btnRefreshMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateMember.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new updateMember().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asdasdasdsda;
    private javax.swing.JLabel btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tAge;
    private javax.swing.JTextField tEmail;
    private javax.swing.JTextField tId;
    private javax.swing.JTextField tName;
    private javax.swing.JTextField tPayment;
    private javax.swing.JTextField tPhone;
    private javax.swing.JTextField tSearch;
    private javax.swing.JComboBox<String> tTime;
    // End of variables declaration//GEN-END:variables
    private void refresh() {
        tId.setText("");
        tName.setText("");
        tPhone.setText("");
        tEmail.setText("");
        tTime.setSelectedItem("");
        tAge.setText("");
        tPayment.setText("");
    }
}
